<?php

namespace Agence\AgenceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DanseusesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DanseusesRepository extends EntityRepository
{
	public function findArray($array)
	{
		$qb = $this->createQueryBuilder('u')
			->Select('u')
			->Where('u.id IN (:array)')
			->setParameter('array', $array);	

			return $qb->getQuery()->getResult();
	}

	public function byCategorie($categorie)
	{
		// qb = query builder
		$qb = $this->createQueryBuilder('u')
		// on selection dans les Danseuses
			->select('u')
			->where('u.categorie = :categorie')
			->orderBy('u.id')
			->setParameter('categorie', $categorie);
			// on retourne le resultat par accueil
		return $qb->getQuery()->getResult();	
	}
}
