<?php

namespace Agence\AgenceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DanseusesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DanseusesRepository extends EntityRepository
{
}
