<?php

namespace Agence\AgenceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MediaGalerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaGalerieRepository extends EntityRepository
{
}
