agence_admin_categories:
    resource: "@AgenceBundle/Resources/config/routing/categories.yml"
    prefix:   /admin/categories

agence_pages_danseuses:
    resource: "@AgenceBundle/Resources/config/routing/danseuses.yml"
    prefix:   /pages/danseuses



produits:
    path:     /
    defaults: { _controller: AgenceBundle:Produits:produits }

presentation:
    path:     /presentation/{id}
    defaults: { _controller: AgenceBundle:Presentation:presentation }

panier:
    path:     /panier
    defaults: { _controller: AgenceBundle:Panier:panier }

ajouter:
    path:     /ajouter/{id}
    defaults: { _controller: AgenceBundle:Panier:ajouter }

supprimer:
    path:     /supprimer/{id}
    defaults: { _controller: AgenceBundle:Panier:supprimer }

livraison:
    path:     /panier/livraison
    defaults: { _controller: AgenceBundle:Panier:livraison }

validation:
    path:     /panier/validation
    defaults: { _controller: AgenceBundle:Panier:validation }

validationCommande:
    pattern: /api/banque/{id}
    defaults: { _controller: AgenceBundle:Commande:validationCommande }

livraisonAdresseSuppression:
    path:     /panier/livraison/adresse/suppression/{id}
    defaults: { _controller: AgenceBundle:Panier:adresseSuppression }

test:
    path:     /test
    defaults: { _controller: AgenceBundle:Test:testFormulaire }