produits:
    path:     /
    defaults: { _controller: AgenceBundle:Produits:produits }

presentation:
    path:     /produit
    defaults: { _controller: AgenceBundle:Produits:presentation }

panier:
    path:     /panier
    defaults: { _controller: AgenceBundle:Panier:panier }

livraison:
    path:     /panier/livraison
    defaults: { _controller: AgenceBundle:Panier:livraison }

validation:
    path:     /panier/validation
    defaults: { _controller: AgenceBundle:Panier:validation }

test:
    path:     /test
    defaults: { _controller: AgenceBundle:Test:ajouter }    